json_datapipeline:
  outputs:
    dev:
      account: wt08219.ap-south-1
      database: dbt_db
      password: Icui4cu@
      role: dbt_role
      schema: gold
      threads: 1
      type: snowflake
      user: vivek
      warehouse: dbt_wh
  target: dev
  config:
    send_anonymous_usage_stats: False
    log_path: /tmp/dbt/logs