name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: dbt-action (deps)
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt deps --profiles-dir ."

    - name: dbt-action (test)
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt test --profiles-dir ."

    - name: dbt-action (run)
      if: ${{ success() }}
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt run --profiles-dir ."
