name: CI/CD Pipeline

on:
  pull_request_review:
    types: [submitted]

jobs:
  build_and_test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: dbt:latest
        load: true  # Important: this makes the built image available to subsequent steps

    - name: dbt-action (deps)
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt deps --profiles-dir ."

    - name: dbt-action (test)
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt test --profiles-dir ."

    - name: Push to Amazon ECR
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/dbt:latest

    - name: dbt-action (run)
      if: ${{ success() }}
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt run --profiles-dir ."
