name: CI/CD Pipeline

on:
  pull_request_review:
    types: [edited, submitted]
    branches:
      - main

jobs:

  dbt-test:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: dbt:latest
          load: true

      - name: dbt-action (deps)
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps --profiles-dir ."

      - name: dbt-action (test)
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test --profiles-dir ."

  build-and-push:
    if: ${{ github.event.pull_request.merged == true && github.ref == 'refs/heads/main' }}
    needs: dbt-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/viv:latest

      - name: dbt-action (run)
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --profiles-dir ."
