name: CI/CD Pipeline

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  dbt-test:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: dbt-action (deps)
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps --profiles-dir ."

      - name: dbt-action (test)
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test --profiles-dir ."
